# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73a0b3b88831b23b42092a1870600dd051bcb0ac82736cb9d968f49d0c11eefcde2906c6189052d0069894288776abee50f9edcd9758dca8d2e733042f695f46

test:
  secret_key_base: 70f5399865261183d216b924929e0a22fa33280307cce7fe651c511d090a8a1dca4d00e31fdc1107dc656516fe369648320840286efcda3257c7e73f8a3e5d52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
